// All UI strings — edit here to change copy without touching components
export const S = {
  nav: {
    home: 'Acasă',
    rooms: 'Camere',
    about: 'Despre noi',
    contact: 'Contact',
    call: 'Sună acum',
  },
  hero: {
    badge: 'Moeciu de Sus · Brașov',
    title: 'Casa din Livadă',
    subtitle: 'Oaza ta de liniște la poalele Branului',
    body: 'Pensiune de familie cu vedere la munți, grădină înflorită și mic dejun proaspăt în fiecare dimineață. La 5 minute de Castelul Bran.',
    ctaRooms: 'Vezi camerele',
    ctaBook: 'Rezervă acum',
  },
  whyUs: {
    title: 'De ce să ne alegi',
    subtitle: 'Experiente autentice în inima Branului',
    items: [
      { icon: 'MapPin', title: 'Locație de excepție', desc: 'La 5 minute de Castelul Bran, în mijlocul naturii din Moeciu de Sus' },
      { icon: 'Coffee', title: 'Mic dejun inclus', desc: 'Produse locale, preparate proaspăt în fiecare dimineață' },
      { icon: 'Trees', title: 'Grădină & Terasă', desc: 'Terasă cu vedere la munți, grădină îngrijită și loc de relaxare' },
      { icon: 'Wifi', title: 'WiFi gratuit', desc: 'Internet rapid în toată pensiunea, inclusiv în grădină' },
    ],
  },
  rooms: {
    title: 'Camerele noastre',
    subtitle: 'Fiecare cameră a fost gândită pentru confortul tău',
    viewDetails: 'Vezi detalii',
    perNight: '/ noapte',
    persons: 'persoane',
    person: 'persoană',
    available: 'Disponibilă',
    unavailable: 'Indisponibilă',
    noRooms: 'Nu există camere disponibile momentan.',
    viewAll: 'Vezi toate camerele',
    back: 'Înapoi la camere',
  },
  experiences: {
    title: 'Experiențe în zonă',
    subtitle: 'Descoperă frumusețile din jurul nostru',
    items: [
      { icon: 'Mountain', title: 'Drumeții montane', desc: 'Trasee marcate pentru toate nivelurile, cu peisaje de poveste spre Bucegi și Piatra Craiului' },
      { icon: 'Castle', title: 'Castelul Bran', desc: 'La 5 minute — legendarul castel al Contesei Dracula, deschis zilnic pentru vizitare' },
      { icon: 'SkiingIcon', title: 'Schi Poiana Brașov', desc: 'La 30 de minute — cea mai populară stațiune de schi din România' },
      { icon: 'Bike', title: 'Ture ATV & Bicicletă', desc: 'Trasee off-road și piste ciclabile prin păduri și fânețe' },
    ],
  },
  testimonials: {
    title: 'Ce spun oaspeții noștri',
    subtitle: 'Experiențe autentice împărtășite de familia noastră de oaspeți',
    items: [
      {
        name: 'Andreea M.',
        location: 'București',
        rating: 5,
        text: 'Am petrecut un weekend de vis la Casa din Livadă. Camera a fost impecabilă, micul dejun delicios, iar priveliștea de pe terasă — de neuitat. Cu siguranță ne vom întoarce!',
      },
      {
        name: 'Familia Ionescu',
        location: 'Cluj-Napoca',
        rating: 5,
        text: 'Am venit cu copiii și a fost alegerea perfectă. Grădina mare, oameni prietenoși și locație excelentă. Am ajuns la Castelul Bran în 5 minute. Totul a depășit așteptările.',
      },
      {
        name: 'Radu & Maria',
        location: 'Brașov',
        rating: 5,
        text: 'Suita Panoramic a fost o revelație. Jacuzzi-ul, balconul cu vedere la munți, micul dejun servit în cameră... exact ce ne trebuia pentru aniversarea noastră. Mulțumim!',
      },
      {
        name: 'Cristian T.',
        location: 'Timișoara',
        rating: 5,
        text: 'Am venit pentru drumeții și am găsit un colț de rai. Gazdele sunt extraordinare, știu tot despre zona montană și ne-au recomandat trasee superbe. Revin cu siguranță.',
      },
    ],
  },
  location: {
    title: 'Unde ne găsești',
    subtitle: 'În inima satului Moeciu de Sus, la poalele Branului',
    address: 'Adresă',
    phone: 'Telefon',
    email: 'Email',
    reception: 'Recepție',
    directions: 'Obține direcții',
  },
  contact: {
    title: 'Contactează-ne',
    subtitle: 'Suntem aici pentru tine. Răspundem în maxim 2 ore.',
    pageTitle: 'Contact',
    pageSubtitle: 'Ai întrebări? Suntem bucuroși să te ajutăm.',
    namePlaceholder: 'Numele tău',
    phonePlaceholder: '+40 7XX XXX XXX',
    emailPlaceholder: 'adresa@email.com',
    messagePlaceholder: 'Cum te putem ajuta? Perioada dorită, tipul camerei, cerințe speciale...',
    send: 'Trimite mesajul',
    sending: 'Se trimite...',
    success: 'Mesaj trimis!',
    successMessage: 'Te vom contacta în maxim 2 ore. Poți suna direct la',
    error: 'Completează câmpurile obligatorii.',
    errorServer: 'Eroare la trimiterea mesajului. Încearcă din nou.',
  },
  about: {
    title: 'Povestea noastră',
    pageTitle: 'Despre Casa din Livadă',
    pageSubtitle: 'O poveste despre oameni, natură și ospitalitate autentică',
    story: [
      'Casa din Livadă a luat naștere din dragostea noastră pentru Moeciu — un loc unde natura, liniștea și autenticitatea se împletesc armonios. Construită în stil tradițional montan, pensiunea noastră a fost gândită ca o a doua casă pentru oaspeții care caută o evadare din agitația urbană.',
      'Familia noastră a locuit în această zonă de generații. Bunicii noștri aveau o livadă de meri care dă și azi roade în septembrie — de acolo vine și numele casei. Am transformat gospodăria ancestrală păstrând sufletul original: lemn, piatră, autenticitate.',
      'Fiecare cameră a fost decorată cu grijă, mobilierul este lucrat manual de meșteri locali, iar micul dejun este pregătit cu produse de la gospodăriile din sat: brânzeturi, mezeluri, ouă de la găinile noastre și gemuri de casă.',
    ],
    facilities: {
      title: 'Facilități generale',
      items: [
        { icon: 'Car', label: 'Parcare gratuită' },
        { icon: 'Trees', label: 'Grădină de 2000 mp' },
        { icon: 'Flame', label: 'Terasă BBQ' },
        { icon: 'UtensilsCrossed', label: 'Bucătărie comună' },
        { icon: 'Baby', label: 'Loc de joacă copii' },
        { icon: 'Wifi', label: 'WiFi gratuit' },
        { icon: 'Coffee', label: 'Mic dejun inclus' },
        { icon: 'PawPrint', label: 'Animale de companie acceptate' },
      ],
    },
  },
  booking: {
    title: 'Rezervă această cameră',
    choosePeriod: 'Alege perioada',
    checkin: 'Check-in',
    checkout: 'Check-out',
    nights: 'nopți',
    night: 'noapte',
    estimatedTotal: 'Total estimat',
    priceNote: 'Prețul final se confirmă la check-in.',
    name: 'Nume complet',
    namePlaceholder: 'Ion Popescu',
    phone: 'Telefon',
    phonePlaceholder: '+40 7XX XXX XXX',
    email: 'Email (opțional)',
    emailPlaceholder: 'ion@exemplu.ro',
    guests: 'Număr persoane',
    notes: 'Mențiuni speciale (opțional)',
    notesPlaceholder: 'Cereri speciale, ora sosirii, etc.',
    submit: 'Trimite cererea de rezervare',
    submitting: 'Se trimite...',
    disclaimer: 'Rezervarea va fi confirmată telefonic în maxim 2 ore. Nu se percepe avans.',
    errorPeriod: 'Selectează perioada de ședere.',
    errorOverlap: 'Camera nu este disponibilă în intervalul selectat.',
    errorServer: 'Eroare la salvarea rezervării. Încearcă din nou sau contactează-ne direct.',
    errorRequired: 'Numele și telefonul sunt obligatorii.',
    errorCapacity: 'Numărul de persoane depășește capacitatea camerei.',
  },
  confirmation: {
    title: 'Cerere trimisă cu succes!',
    subtitle: 'Rezervarea ta este în așteptarea confirmării.',
    body: 'Te vom contacta telefonic în maxim 2 ore pentru a confirma disponibilitatea și detaliile șederii.',
    callNote: 'Nu ai primit niciun apel în 2 ore? Sună-ne direct:',
    backToRooms: 'Înapoi la camere',
    backHome: 'Acasă',
  },
  footer: {
    tagline: 'Oaza ta de liniște la poalele Branului',
    quickLinks: 'Link-uri rapide',
    contact: 'Contact',
    copyright: 'Toate drepturile rezervate.',
    madeBy: 'Site realizat de',
    brand: 'StartCo',
  },
  filters: {
    all: 'Toate',
    capacity: 'Capacitate',
    price: 'Preț',
    priceLow: 'Preț crescător',
    priceHigh: 'Preț descrescător',
    persons2: '2 persoane',
    persons3: '3 persoane',
    persons4: '4+ persoane',
    noResults: 'Nicio cameră nu corespunde filtrelor.',
    reset: 'Resetează filtrele',
    found1: 'cameră găsită',
    foundMany: 'camere găsite',
  },
  admin: {
    pendingLabel: 'În așteptare',
    approvedLabel: 'Aprobată',
    rejectedLabel: 'Respinsă',
    cancelledLabel: 'Anulată',
  },
} as const
